/* 
 * HelloWebApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using HelloWebApi.Service.Client;
using HelloWebApi.Service.Api;
using HelloWebApi.Service.Model;

namespace HelloWebApi.Service.Test
{
    /// <summary>
    ///  Class for testing EmployeesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EmployeesApiTests
    {
        private EmployeesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EmployeesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmployeesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EmployeesApi
            //Assert.IsInstanceOfType(typeof(EmployeesApi), instance, "instance is a EmployeesApi");
        }

        
        /// <summary>
        /// Test EmployeesDelete
        /// </summary>
        [Test]
        public void EmployeesDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.EmployeesDelete(id);
            
        }
        
        /// <summary>
        /// Test EmployeesGet
        /// </summary>
        [Test]
        public void EmployeesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.EmployeesGet();
            //Assert.IsInstanceOf<List<Employee>> (response, "response is List<Employee>");
        }
        
        /// <summary>
        /// Test EmployeesGet_0
        /// </summary>
        [Test]
        public void EmployeesGet_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.EmployeesGet_0(id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test EmployeesPost
        /// </summary>
        [Test]
        public void EmployeesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //instance.EmployeesPost(value);
            
        }
        
        /// <summary>
        /// Test EmployeesPut
        /// </summary>
        [Test]
        public void EmployeesPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //string value = null;
            //instance.EmployeesPut(id, value);
            
        }
        
    }

}
