/* 
 * HelloWebApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HelloWebApi.Service.Api;
using HelloWebApi.Service.Model;
using HelloWebApi.Service.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HelloWebApi.Service.Test
{
    /// <summary>
    ///  Class for testing Employee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmployeeTests
    {
        // TODO uncomment below to declare an instance variable for Employee
        //private Employee instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Employee
            //instance = new Employee();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Employee
        /// </summary>
        [Test]
        public void EmployeeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Employee
            //Assert.IsInstanceOfType<Employee> (instance, "variable 'instance' is a Employee");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'BirthDay'
        /// </summary>
        [Test]
        public void BirthDayTest()
        {
            // TODO unit test for the property 'BirthDay'
        }

    }

}
